// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SchedulesColumns holds the columns for the "schedules" table.
	SchedulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "start_at", Type: field.TypeTime},
	}
	// SchedulesTable holds the schema information for the "schedules" table.
	SchedulesTable = &schema.Table{
		Name:       "schedules",
		Columns:    SchedulesColumns,
		PrimaryKey: []*schema.Column{SchedulesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "create_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserSchedulesColumns holds the columns for the "user_schedules" table.
	UserSchedulesColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "schedule_id", Type: field.TypeInt},
	}
	// UserSchedulesTable holds the schema information for the "user_schedules" table.
	UserSchedulesTable = &schema.Table{
		Name:       "user_schedules",
		Columns:    UserSchedulesColumns,
		PrimaryKey: []*schema.Column{UserSchedulesColumns[0], UserSchedulesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_schedules_user_id",
				Columns:    []*schema.Column{UserSchedulesColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_schedules_schedule_id",
				Columns:    []*schema.Column{UserSchedulesColumns[1]},
				RefColumns: []*schema.Column{SchedulesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SchedulesTable,
		UsersTable,
		UserSchedulesTable,
	}
)

func init() {
	UserSchedulesTable.ForeignKeys[0].RefTable = UsersTable
	UserSchedulesTable.ForeignKeys[1].RefTable = SchedulesTable
}
